#index:
#    path: /
#    controller: App\Controller\DefaultController::index
home_index:
    path: /
    controller: App\Controller\HomeController::index
test_page:
    path: /test
    controller: App\Controller\TestController::index
security_login:
    path: /login
    controller: App\Controller\SecurityController::login